### ISSUE TITLE
Define access control hierarchy

### ISSUE THREAD

**Issue by agentrickard** [agentrickard/workbench_access#5]
The correct method would seem to be to create Plugins that can be registered / deregistered. Those plugins would follow an interface defined by WA for building, storing, and matching access rules to specific contexts.

That is, plugins would replace the "module" includes from the D7 version.

**Comment by Crell** [comment]
That sounds correct, yes.  WA would define a plugin type, AccessControlHierarchy, with interface and a utility trait or base class.  Then any module (including WA) would be able to define any number of ACH plugins.  Users would then pick the plugin to use and configure it.

I'm trying to think of a good core example there...  Maybe Mail backends?  Possibly image toolkits?

**Comment by agentrickard** [comment]
Or maybe just Blocks?

**Comment by Crell** [comment]
No, Blocks are used in a context where you will always be creating multiple block instances and using them in parallel.

This is a case where the site has only one active instance at a time.  Normally I'd say that you then do NOT want to use Plugins, just a service, but each implementation has its own configuration.  Plugins are a better fit when there's variable user configuration involved, but the usage pattern is different than blocks or text formats.

**Comment by agentrickard** [comment]
Well, that's the big question: How do users enable/select the hierarchy.

In D7, we have a registration hook and the user selects. You could, however, make entire submodules that people have to enable. The advantage to the hook / plugin approach is that you can restrict users to one plugin at a time.

Is there are argument to be made that a Service is the better choice? I'm not clear on what that architecture would look like. Plugin registration seems more "natural" to me.

**Comment by agentrickard** [comment]
In the 5-plugins branch.
